### ISSUE TITLE
Unable to make requests on localhost

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#469]
I'm unable to make requests to the backend in my local dev environment. I followed all the setup steps in the README.

1. `yarn dev` in the root
2. `cd frontend && yarn start`
3. open http://localhost:8080
4. attempt to sign in

<img width="1522" alt="Screen Shot 2021-11-26 at 10 49 16 AM" src="https://user-images.githubusercontent.com/3411183/143621392-89dc877d-c66a-4eec-8d42-bb17bef52c42.png">

**Comment by coderbyheart** [comment]
Try setting the `ORIGIN` environment variable to `http://localhost:8080/`, before starting the backend server.

**Comment by coderbyheart** [comment]
Hm, but that's the default.
https://github.com/distributeaid/shipment-tracker/blob/a99ec457902a36910da0fc7c951e2a2f39ee41e4/src/server/dev.ts#L12

**Comment by deammer** [comment]
Yeah the `origin` is on port `8080` which seems right. The frontend also runs on `8080`, which seems correct? I've tried hitting the API at port `8080` as well but that throws a 404 as expected.

**Comment by coderbyheart** [comment]
I tried reproducing it, but for me it works.

Could you copy the full request and response?
And the logs from the backend?

It looks like that the backend is actually not running at `localhost:3000`, because the response is HTML in your case.

Mine looks a little different:
![Screenshot_20211127_092201](https://user-images.githubusercontent.com/188915/143674062-8223824d-f954-429e-bfe1-b8a1f251d371.png)

**Comment by coderbyheart** [comment]
Can you copy the curl request from the Chrome console and run it from your terminal?

**Comment by deammer** [comment]
> It looks like that the backend is actually not running at localhost:3000, because the response is HTML in your case.

That was a nice catch: I had a server running on that same port and didn't know about it. Once I killed the process, things started working again.

Thank you for the debugging help! Closing this issue.
