### ISSUE TITLE
Should we separate the backend and frontend?

### ISSUE THREAD

**Issue by deammer** [distributeaid/shipment-tracker#73]
This has come up multiple times so I want to start a discussion and get some opinions. I'll try to maintain the table of pros and cons below.

There are 2 main points:
1. should we adopt a sibling structure/monorepo approach for the backend and frontend directories?

|Pros|Cons|
|---|---|
|No more [package conflicts](https://github.com/facebook/create-react-app/issues/1795#issuecomment-357353472) related to multiple package.json files|Codegen will be more complicated: how do we share code?|

2. should we host the backend and frontend separately?

|Yes, separate|No, serve from a single server|
|---|---|
|Take advantage of Netlify's CDN for free|Only need to maintain 1 service (Heroku, in our case)|
|We can scale the frontend and backend separately to keep costs low||
|The backend will work the same in all environments, instead of having environment-specific code such as serving the frontend pages||

**Comment by bion** [comment]
In summary, I think splitting them would increase devops overhead considerably for little in the way of tangible gains. I'd rather focus on building the app's functionality and wait until we are experiencing problems that we think can best be solved by taking either of these actions before pursuing them.

### package conflicts

Are there package conflicts we expect to see? From the link it looked like there were some things related to webpack and npm, of which we're currently using neither.

### code sharing

In addition to codegen. It seems likely there will be more and more code we want to share between the backend and frontend: validation logic, calculations for weight and dimensions, routes, and more. I don't see a way of changing the directory structure of the project that doesn't make doing this harder.

### scaling, CDN

If the app is extremely successful beyond expectations we will have at most several hundred (total, non-simultaneous) users by the end of 2021. That level of load can be easily handled with a single small server though we should have two so there's redundancy.

AFAIK a CDN is helpful for reducing time to first render and reducing load on backend application servers (since they won't have to serve static assets). Time-to-first render isn't of much concern for us since SEO is not a priority. After initial load assets will be cached and a CDN won't help with latency.

### environment consistency

The differences are relatively minor and exist to provide convenience for the frontend dev experience (i.e. the react dev server). We can run the app locally with its normal behavior by running `pushd frontend && yarn build && popd && yarn build && yarn start`.

**Comment by deammer** [comment]
Things work pretty well so let's keep the current system.
